{
 "title": "Tickr",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(tickr_bot_heartbeat_failures,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(tickr_bot_heartbeat_failures{job=\"$job\"},instance)"
    }
   },
   {
    "name": "bots",
    "label": "Bots",
    "query": {
     "query": "label_values(tickr_bot_heartbeat_failures{job=\"$job\", instance=\"$instance\"},bot)"
    }
   },
   {
    "name": "steamids",
    "label": "SteamIDs",
    "query": {
     "query": "label_values(tickr_bot_heartbeat_failures{job=\"$job\", instance=\"$instance\", steamid!=\"0\"},steamid)"
    }
   },
   {
    "name": "http_client_server_addresses",
    "query": {
     "query": "label_values(http_client_request_duration_seconds_sum{job=\"$job\", instance=\"$instance\", server_address!~\"$excluded_servers\"},server_address)"
    }
   },
   {
    "name": "excluded_endpoint",
    "label": "ASP.NET: Exclude metrics endpoint",
    "query": "yes : /Api/metrics, no : ''"
   },
   {
    "name": "excluded_servers",
    "label": "HTTP Client: Exclude *.steamserver.net",
    "query": "yes : (cmp|ext)[0-9]+-[a-z]+[0-9]+\\.steamserver\\.net, no : ''"
   }
  ]
 },
 "panels": [
  {
   "title": "Tickr Variant",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tickr_build_info{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{variant}}"
    }
   ]
  },
  {
   "title": "Tickr Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tickr_build_info{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": ".NET Framework",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tickr_runtime_info{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{framework}}"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tickr_runtime_info{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{runtime}}"
    }
   ]
  },
  {
   "title": "Operating System",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tickr_runtime_info{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{operating_system}}"
    }
   ]
  },
  {
   "title": "Global statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(tickr_bots{job=\"$job\", instance=\"$instance\", state=\"configured\"}) by (job, instance)",
       "legendFormat": "configured"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 3, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(tickr_bots{job=\"$job\", instance=\"$instance\", state!=\"configured\", state!=\"farming\"}) by (job, instance, state)",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(tickr_bots{job=\"$job\", instance=\"$instance\", state=\"farming\"}) by (job, instance)",
       "legendFormat": "farming"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(tickr_active_plugins{job=\"$job\", instance=\"$instance\", type=\"\"}) by (job, instance)",
       "legendFormat": "Plugins"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 15, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(tickr_active_plugins{job=\"$job\", instance=\"$instance\", type=\"official\"}) by (job, instance)",
       "legendFormat": "Official Plugins"
      },
      {
       "expr": "avg(tickr_active_plugins{job=\"$job\", instance=\"$instance\", type=\"custom\"}) by (job, instance)",
       "legendFormat": "Custom Plugins"
      }
     ]
    },
    {
     "title": "IPC banned IPs",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(tickr_ipc_banned_ips{job=\"$job\", instance=\"$instance\"}) by (job, instance)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Bot statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Farming time remaining",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "expr": "avg(tickr_bot_farming_time_remaining_minutes{job=\"$job\", instance=\"$instance\", bot=~\"$bots\", steamid=~\"$steamids\", steamid!=\"0\"}) by (job, instance, bot, steamid)",
       "legendFormat": "{{bot}}"
      }
     ]
    },
    {
     "title": "Wallet balance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "avg(tickr_bot_wallet_balance{job=\"$job\", instance=\"$instance\", bot=~\"$bots\", steamid=~\"$steamids\", steamid!=\"0\", currency!~\"CNY|KWD|VND\"} / 100) by (job, instance, bot, steamid, currency)",
       "legendFormat": "{{bot}} ({{currency}})"
      },
      {
       "expr": "avg(tickr_bot_wallet_balance{job=\"$job\", instance=\"$instance\", bot=~\"$bots\", steamid=~\"$steamids\", steamid!=\"0\", currency=~\"CNY|VND\"} / 10) by (job, instance, bot, steamid, currency)",
       "legendFormat": "{{bot}} ({{currency}})"
      },
      {
       "expr": "avg(tickr_bot_wallet_balance{job=\"$job\", instance=\"$instance\", bot=~\"$bots\", steamid=~\"$steamids\", steamid!=\"0\", currency=~\"KWD\"} / 1000) by (job, instance, bot, steamid, currency)",
       "legendFormat": "{{bot}} ({{currency}})"
      }
     ]
    },
    {
     "title": "BGR key remaining",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 85 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(tickr_bot_bgr_keys_remaining{job=\"$job\", instance=\"$instance\", bot=~\"$bots\", steamid=~\"$steamids\", steamid!=\"0\"}) by (job, instance, bot, steamid)",
       "legendFormat": "{{bot}}"
      }
     ]
    },
    {
     "title": "Heartbeat failures",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 85 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(tickr_bot_heartbeat_failures{job=\"$job\", instance=\"$instance\", bot=~\"$bots\", steamid=~\"$steamids\", steamid!=\"0\"}) by (job, instance, bot, steamid)",
       "legendFormat": "{{bot}}"
      }
     ]
    },
    {
     "title": "Friends",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 91 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(tickr_bot_friends{job=\"$job\", instance=\"$instance\", bot=~\"$bots\", steamid=~\"$steamids\", steamid!=\"0\"}) by (job, instance, bot, steamid)",
       "legendFormat": "{{bot}}"
      }
     ]
    },
    {
     "title": "Groups",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 91 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(tickr_bot_clans{job=\"$job\", instance=\"$instance\", bot=~\"$bots\", steamid=~\"$steamids\", steamid!=\"0\"}) by (job, instance, bot, steamid)",
       "legendFormat": "{{bot}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(max_over_time(process_runtime_dotnet_gc_committed_memory_size_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "GC Committed Memory Size"
      },
      {
       "expr": "avg(max_over_time(process_runtime_dotnet_gc_objects_size_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "GC Objects size"
      },
      {
       "expr": "avg(max_over_time(dotnet_gc_last_collection_memory_committed_size_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "GC Committed Memory Size"
      }
     ]
    },
    {
     "title": "Heap Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(max_over_time(process_runtime_dotnet_gc_heap_size_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (job, instance, generation)",
       "legendFormat": "{{generation}}"
      },
      {
       "expr": "avg(max_over_time(dotnet_gc_last_collection_heap_size_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (job, instance, gc_heap_generation)",
       "legendFormat": "{{gc_heap_generation}}"
      }
     ]
    },
    {
     "title": "Heap Fragmentation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(max_over_time(process_runtime_dotnet_gc_heap_fragmentation_size_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (job, instance, generation)",
       "legendFormat": "{{generation}}"
      },
      {
       "expr": "avg(max_over_time(dotnet_gc_last_collection_heap_fragmentation_size_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (job, instance, gc_heap_generation)",
       "legendFormat": "{{gc_heap_generation}}"
      }
     ]
    },
    {
     "title": "Garbage Collections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg(rate(process_runtime_dotnet_gc_collections_count_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (job, instance, generation)",
       "legendFormat": "{{generation}}"
      },
      {
       "expr": "avg(rate(dotnet_gc_collections_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (job, instance, gc_heap_generation)",
       "legendFormat": "{{gc_heap_generation}}"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg(rate(process_runtime_dotnet_exceptions_count_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": " Exceptions"
      },
      {
       "expr": "avg(rate(dotnet_exceptions_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": " Exceptions"
      }
     ]
    },
    {
     "title": "Thread Pool Threads",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(max_over_time(process_runtime_dotnet_thread_pool_threads_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "Thead Pool Threads"
      },
      {
       "expr": "avg(max_over_time(dotnet_thread_pool_thread_count_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "Thead Pool Threads"
      }
     ]
    },
    {
     "title": "Thread Pool Queue Length",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(max_over_time(process_runtime_dotnet_thread_pool_queue_length{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "Thread Pool Queue Length"
      },
      {
       "expr": "avg(max_over_time(dotnet_thread_pool_queue_length_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "Thread Pool Queue Length"
      }
     ]
    }
   ]
  },
  {
   "title": "ASP.NET",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", http_route!=\"$excluded_endpoint\"}[$__rate_interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", http_route!=\"$excluded_endpoint\"}[$__rate_interval])) by (le))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", http_route!=\"$excluded_endpoint\"}[$__rate_interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", http_route!=\"$excluded_endpoint\"}[$__rate_interval])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.98, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", http_route!=\"$excluded_endpoint\"}[$__rate_interval])) by (le))",
       "legendFormat": "p98"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", http_route!=\"$excluded_endpoint\"}[$__rate_interval])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", http_route!=\"$excluded_endpoint\"}[$__rate_interval])) by (le))",
       "legendFormat": "p99.9"
      }
     ]
    },
    {
     "title": "Errors Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", http_response_status_code=~\"4..|5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "All"
      },
      {
       "expr": "sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", http_response_status_code=~\"4..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "4XX"
      },
      {
       "expr": "sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", http_response_status_code=~\"5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "5XX"
      }
     ]
    },
    {
     "title": "Current Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "sum(kestrel_active_connections{job=\"$job\", instance=\"$instance\"})",
       "legendFormat": "Active connections"
      }
     ]
    },
    {
     "title": "Current Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 40 },
     "targets": [
      {
       "expr": "sum(http_server_active_requests{job=\"$job\", instance=\"$instance\"})",
       "legendFormat": "Active requests"
      }
     ]
    },
    {
     "title": "Total Requests",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", http_route!~\"$excluded_endpoint\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Unhandled Exceptions",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", error_type!=\"\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests Secured",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 44 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum (max_over_time(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", http_route!=\"$excluded_endpoint\"}[$__rate_interval])) by (url_scheme)",
       "legendFormat": "{{scheme}}"
      }
     ]
    },
    {
     "title": "Requests HTTP Protocol",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 44 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum (label_replace(max_over_time(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", http_route!=\"$excluded_endpoint\"}[$__rate_interval]), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")) by (method_route)",
       "legendFormat": "{{protocol}}"
      }
     ]
    },
    {
     "title": "Top 10 Requested Endpoints",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "topk(10, sum (label_join(max_over_time(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", http_route!=\"\", http_route!=\"$excluded_endpoint\"}[$__rate_interval]), \"method_route\", \" \", \"http_request_method\", \"http_route\")) by (http_route, http_request_method, method_route))",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Top Status Codes",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "expr": "topk(30, sum (max_over_time(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", http_route!=\"$excluded_endpoint\"}[$__rate_interval])) by (http_response_status_code))",
       "legendFormat": "{{http_response_status_code}}"
      }
     ]
    },
    {
     "title": "Top 10 Unhandled Exception Endpoints",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "topk(10, sum (label_join(max_over_time(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", http_route!=\"\", error_type!=\"\"}[$__rate_interval]), \"method_route\", \" \", \"http_request_method\", \"http_route\")) by (http_route, http_request_method, method_route))",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Active connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "targets": [
      {
       "expr": "avg(kestrel_active_connections{job=\"$job\", instance=\"$instance\"}) by (job, instance, server_address, server_port)",
       "legendFormat": "{{server_address}}:{{server_port}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(http_client_open_connections{job=\"$job\", instance=\"$instance\", http_connection_state=\"active\"}) by (http_connection_state, url_scheme, server_address)",
       "legendFormat": "{{http_connection_state}} {{url_scheme}}://{{server_address}}/"
      }
     ]
    },
    {
     "title": "Idle connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(http_client_open_connections{job=\"$job\", instance=\"$instance\", http_connection_state=\"idle\"}) by (http_connection_state, url_scheme, server_address)",
       "legendFormat": "{{http_connection_state}} {{url_scheme}}://{{server_address}}/"
      }
     ]
    },
    {
     "title": "Requests duration by server, method and status code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(http_client_request_duration_seconds_sum{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (job, instance, http_request_method, url_scheme, server_address, http_response_status_code)",
       "legendFormat": "{{http_request_method}} {{url_scheme}}://{{server_address}}/ {{http_response_status_code}}"
      }
     ]
    },
    {
     "title": "Request duration by server",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(http_client_request_duration_seconds_sum{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (url_scheme, server_address)",
       "legendFormat": "{{http_request_method}} {{url_scheme}}://{{server_address}}/ {{http_response_status_code}}"
      }
     ]
    },
    {
     "title": "$http_client_server_addresses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "repeat": "http_client_server_addresses",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(http_client_request_duration_seconds_sum{job=\"$job\", instance=\"$instance\", server_address=~\"$http_client_server_addresses\", http_response_status_code!=\"\"}[$__rate_interval])) by (http_request_method, http_response_status_code) > 0",
       "legendFormat": "{{http_request_method}} -> {{http_response_status_code}}"
      }
     ]
    }
   ]
  }
 ]
}